# Generated by Django 6.0.4 on 2026-07-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0004_pot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pot',
            old_name='quantity',
            new_name='stock',
        ),
        migrations.AddField(
            model_name='pot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pots/'),
        ),
    ]
