# Generated by Django 6.0.4 on 2026-07-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0005_rename_quantity_pot_stock_pot_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
